spring.datasource.url=jdbc:postgresql://db.ujjyltittlfneeqszwqf.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=SDre395%#jsd&@pfemfed#45
spring.datasource.driver-class-name=org.postgresql.Driver